---
title: "More information"
author: "Jiaqi Li and Mackie Zhou"
date: "Last updated on `r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    df_print: kable
---

<!--
Comments in HTML are like this! 
-->

# SECTION NAME

Write your "more information" section here.

## Subsection name

Write a second `more_info.html` page going more in-depth for people who want more details. In should have

1. Between 2-3 more visualizations.
1. No more than 500 words of text

```{r, echo = FALSE}
# load packages
library(tidyverse)
library(gridExtra)

library(sf)
library(maps)
library(USAboundaries)
library(plotly)
library(widgetframe)

# read the ecudational attainment df into R
Edu_complete <- read_csv("Estimate_Educational_attainment_2017.csv")

# read the suicide df into R
suicide_by_state <- read_csv("Suicide_Mortality_by_State.csv")

# read the 50 state names&codes df into R
State_names <- read_csv("50State_names_and_codes.csv")

# US_map
US_map<-USAboundaries::us_states(resolution = "high") %>%
  mutate(lon = purrr::map_dbl(geometry, ~sf::st_centroid(.x)[[1]]),
         lat = purrr::map_dbl(geometry, ~sf::st_centroid(.x)[[2]]))

```

## Suicide death rate

```{r, echo = FALSE}
# select only data in 2017 and optimize the df
suicide_2017 <- suicide_by_state %>% 
  filter(YEAR=="2017") %>% 
  left_join(State_names, by = c("STATE" = "Code")) %>% 
  rename(CODE = STATE,
         STATE = State) %>%
  arrange( RATE ) %>% 
  select(STATE, CODE, DEATHS, RATE)
# 
# # horizontal bar graph of suicide rate by state
# suicide <- ggplot(data = suicide_2017, 
#        mapping = aes(x = reorder(STATE, -desc(RATE)),
#                      y = RATE)) +
#   geom_col(fill="CornflowerBlue",
#            width = 0.75) +
#   # scale_y_continuous(labels = scales::percent) +
#   labs(x = "State",
#        y = "Suicide Death Rate(%)",
#        title = "Suicide Death Rate by State in 2017") +
#   # theme(text = element_text(size=15)) +
#   coord_flip()
# suicide


#Suicide Rate by State map
suicide_map_df<- US_map %>% 
  left_join(suicide_2017, by=c("stusps"="CODE"))

suicide_map <- ggplot()+
  geom_sf(data = suicide_map_df,
          aes(fill = RATE), 
          color = "white") +
  scale_fill_gradient(low = "#86e884", high = "#244024") +
  labs(x = "Longitude", y = "Latitude", fill = "Suicide Death Rate") +
  coord_sf(xlim = c(-170, -60), ylim = c(24, 72), expand = FALSE)
# suicide_map

ggplotly(suicide_map) %>%
  widgetframe::frameWidget()
# 
# grid.arrange(suicide,
#              arrangeGrob(suicide_map, NA, nrow = 2),
#              ncol = 2)

```

## Estimate educational attainment

```{r, echo = FALSE, fig.height = 15, fig.width = 12}
# select only the state names and the percentages
Edu_percent <- Edu_complete %>%
  select(State, contains("Percent")) %>% 
  select(-(contains("MOE"))) %>% 
  pivot_longer(names_to = "Education", 
               values_to = "Percentage", 
               cols = -State) %>% 
  mutate(Education = str_replace_all(Education, " - Percent", ""))

Edu_percent <- arrange(Edu_percent, Education, Percentage)
Edu_percent$State <- factor(Edu_percent$State, levels = unique(Edu_percent$State)) 

edu <- ggplot(data = Edu_percent, 
       mapping = aes(x = State,
                     y = Percentage, 
                     fill = factor(Education, 
                                   levels=c("Less than high school graduate",
                                            "High school graduate (includes equivalency)",
                                            "Some college or associate's degree",
                                            "Bachelor's degree or higher")))) +
  geom_bar(position="fill", 
           stat="identity",
           width = 0.7) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "State",
       y = "Percentage",
       fill = "Educational Attainment",
       title = "Estimate Educational Attainment of People Aged 18-24 by State in 2017") +
  coord_flip() +
  # theme(text = element_text(size=15)) +
  # guides(fill=guide_legend(ncol=1)) +
  guides(fill = guide_legend(reverse=TRUE, ncol=1)) +
  theme(legend.position="bottom")
edu

# 
# #Education Attainment Map by State in U.S
# edu_map_df<- US_map %>% 
#   left_join(Edu_complete,by=c("name"="State")) %>% 
#   filter(stusps != "DC")
# 
# edu_map <- ggplot()+
#   geom_sf(data = edu_map_df,
#         aes(fill = score), 
#         color = "white") +
#   scale_fill_gradient(low = "lightblue", 
#                       high = "#06154f") +
#   coord_sf(xlim = c(-170, -60), 
#            ylim = c(24, 72), 
#            expand = FALSE)
# edu_map

# ggplotly(edu_map) %>%
#   widgetframe::frameWidget()
```

## Relationship between suicide death rate and education level

```{r, echo = FALSE}
edu_score_suicide <- suicide_2017 %>% 
  inner_join(Edu_complete, by = c("STATE" = "State")) %>% 
  select(-Id, -Id2) %>% 
  rename(Death_Rate = RATE, Education_Level = score) %>% 
  select(STATE, Death_Rate, Education_Level, everything())
# edu_score_suicide

scatter <- ggplot(edu_score_suicide, aes(x = Education_Level, y = Death_Rate)) +
  geom_point() +
  geom_smooth(method = "lm", 
              se = TRUE) +
  labs(x = "Education Level",
       y = "Suicide Death Rate",
       title = "Education Level Score and Suicide Death Rate of 50 US States in 2017")
scatter

```

```{r, echo = FALSE, fig.height = 15, fig.width = 12}
# grid.arrange(edu, scatter, ncol=2)
```

